# Generated by Django 6.0.7 on 2026-07-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0002_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to='profiles.candidateprofile'),
        ),
    ]
